### ISSUE TITLE
Error in rf.crossValidation for rfUtilities 2.1-4

### ISSUE THREAD

**Issue by bi0m3trics** [jeffreyevans/rfUtilities#4]
Hi Jeffrey - it looks like the [Dec 14th 2018 commit](https://github.com/jeffreyevans/rfUtilities/commit/a511ee910e8b32eb87e8f21399599071b0e68958#diff-70b42b94250cb084705b7fde91693a41) introduced an error on line 142, where `sample.sizes` is being called but it appears to have not been initiated in the regression cross-validation code (...this is not the case in the classification cross-validation code on lines 184-187). The following code (running `randomForest` 4.6-14 and `rfUtilities` 2.1-4 in `R` 3.5.2) from the documentation:
```
data(airquality)
airquality <- na.omit(airquality) 
rf.mdl <- randomForest(y=airquality[,"Ozone"], x=airquality[,2:4])
( rf.cv <- rf.crossValidation(rf.mdl, airquality[,2:4], p=0.10, n=99, ntree=501) )
```
produces the following error:
```
Error in sample.int(length(x), size, replace, prob) : 
  object 'sample.sizes' not found
```

**Comment by jeffreyevans** [comment]
Sorry about that, I added a feature request for a classification instance and in mucking with the code broke the regression sampling. It is fixed now. Please install the development version off of GitHub as this will not be on CRAN for a bit.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist / Biometrician
The Nature Conservancy | Global Lands Science Team
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>
